name: audio_playground
description: Flutter project to play with audio.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  dio: ^5.1.1
  # flutter_sound: ^9.2.13
  permission_handler: ^9.2.0
  audioplayers: ^4.1.0
  record: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


